name: Walis Hian-chi Song
title: Independent Researcher
email: walis.hcs@gapp.nthu.edu.tw
location: Tainan, Taiwan
socialLinks:
  - label: Academia.edu
    url: https://nthu.academia.edu/WalisHCS
  - label: X (Twitter)
    url: https://x.com/walis_hcs
